apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress-nginx
  namespace: {{ .Values.k8sJenkinsMgmt.ingress.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.k8sJenkinsMgmt.ingress.jenkinsUriPrefix }}
            backend:
              serviceName: {{ .Values.k8sJenkinsMgmt.ingress.jenkinsDeploymentName }}
              servicePort: 8080
