apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.k8sJenkinsMgmt.ingress.deploymentName }}-lb
  namespace: {{ .Values.k8sJenkinsMgmt.ingress.namespace }}
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  # externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: {{ .Values.k8sJenkinsMgmt.ingress.loadbalancerIp }}
  ports:
    - port: 80
      name: http
      targetPort: 80
    - port: 443
      name: https
      targetPort: 443
  selector:
    # Selects nginx-ingress-controller pods
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx